# GET /api/offers — ресурс возвращает список объявлений;
GET http://localhost:3000/api/offers

###
# GET /api/offers/:offerId — возвращает полную информацию определённого объявления;
GET http://localhost:3000/api/offers/lNfoyA

###
# GET /api/categories — возвращает список категорий;
GET http://localhost:3000/api/categories

###
# POST /api/offers — создаёт новое объявление;
POST http://localhost:3000/api/offers
Content-Type: application/json

{
  "category": ["Разное"],
  "description": "Кажется, что это хрупкая вещь.",
  "picture": "item01.jpg",
  "title": "Куплю Xbox Series X.",
  "sum": 12345,
  "type": "offer"
}

###
# PUT /api/offers/:offerId — редактирует определённое объявление;
PUT http://localhost:3000/api/offers/lNfoyA
Content-Type: application/json

{
  "category": ["Разное"],
  "description": "Кажется, что это хрупкая вещь. Мой дед не мог её сломать.",
  "picture": "item02.jpg",
  "title": "Куплю Xbox Series X.",
  "sum": 54321,
  "type": "offer"
}

###
# DELETE /api/offers/:offerId — удаляет определённое объявление;
DELETE http://localhost:3000/api/offers/lNfoyA

###
# GET /api/offers/:offerId/comments — возвращает список комментариев определённого объявления;
GET http://localhost:3000/api/offers/lNfoyA/comments

###
# DELETE /api/offers/:offerId/comments/:commentId — удаляет из определённой публикации комментарий с идентификатором;
DELETE http://localhost:3000/api/offers/lNfoyA/comments/SA_b34

###
# POST /api/offers/:offerId/comments — создаёт новый комментарий;
POST http://localhost:3000/api/offers/lNfoyA/comments
Content-Type: application/json

{
  "text": "Новый комментарий"
}

###
# Поиск
GET http://localhost:3000/api/search?query=куплю
